---
- name: Eliminar fichero
  hosts: all
  become: yes
  tasks:
    - name: imprime ruta buscada
      debug:
        msg: "{{ tempfile }}"
    - name: Eliminar
      ansible.builtin.file:  
        path: "{{ tempfile }}"
        state: absent
        when: tempfile is defined
        

        
#        state: stopped
#        state: started
#---
#- hosts: all
#  become: yes
#  tasks:
#    - name: Eliminar
#      ansible.builtin.file:
#        path: "{{ tempfile }}"
#        state: absent
#      when: tempfile is defined        
  #       path: /home/hapareja/test/file.txt    #path de pruebas

