---
#- name: Elimina fichero o directorio Linux
  hosts: all
  become: yes
  tasks:
   - name: Eliminar
     ansible.builtin.file:
       path: /home/hapareja/test/file.txt
       state: absent
#pruyebasa
