---
- name: Eliminar fichero
  hosts: all
#  become: yes
  tasks:
    - name: imprime ruta buscada
      debug:
        msg: "{{ tempfile }}"
    - name: Eliminar
      ansible.builtin.file:  
        path: "{{ tempfile }}"
        state: absent
      when: tempfile is defined
      
     
