---
- name: Ejecuta script
  hosts: all
#  become: yes
  tasks:
    - name: Se va a ejecutar el siguiente script
      debug:
        msg: "{{ script.text }}"
        
    - name: Ejecuta un script con argumentos
      ansible.builtin.script: script.text

