---
- name: Ejecuta script
  hosts: all
#  become: yes
  tasks:
#    - name: Se va a ejecutar el siguiente script #se requiere indicar ruta en la misma linea
#      debug:
#        msg: "{{ script_text }}"
#        
#    - name: Ejecuta la linea de comandos
#      ansible.builtin.script: 
#        cmd: "{{ script_text }}"
#    
#####################################################################################
#    - name: Cambia de directorio de trabajo y ejecuta linea de comandos
#      ansible.builtin.shell:
#        cmd: "{{ script_text }}"
#        chdir: "{{ ruta_script }}"
#      register: data_out
#    
#    - debug:
#        msg: Ejecutando "{{ ruta_script }}" "{{ script_text }}"
#    - debug:
#        msg: "{{ data_out }}"
######################################################################################

    - name: Change the working directory to somedir/ before executing the command
      ansible.builtin.shell: sh prueba.sh
      args:
        chdir: /tmp/
